### ISSUE TITLE
Bin Bug

### ISSUE THREAD

**Issue by lukefahr** [mbus/m3-python#2]
m3_ice goc flash PRCv14_sleep_wakeup/PRCv14_sleep_wakeup.bin
INFO	--------------------------------------------------------------------------------
INFO	 -- M3 ICE Interface
INFO
INFO	Guessing ICE is at: /dev/cu.usbserial-A603TU7M
INFO	Connected to serial device at /dev/cu.usbserial-A603TU7M
INFO	This library supports versions...
INFO		0.1
INFO		0.2
INFO		0.3
INFO	This ICE board supports versions...
INFO		0.3 **Chosen version
Traceback (most recent call last):
  File "/usr/local/bin/m3_ice", line 9, in <module>
    load_entry_point('m3==0.4.4', 'console_scripts', 'm3_ice')()
  File "/usr/local/lib/python2.7/site-packages/m3-0.4.4-py2.7.egg/m3/m3_ice.py", line 118, in cmd
    m.args.func()
  File "/usr/local/lib/python2.7/site-packages/m3-0.4.4-py2.7.egg/m3/m3_common.py", line 651, in cmd_flash
    self.m3_ice.read_binfile(self.m3_ice.args.BINFILE)
  File "/usr/local/lib/python2.7/site-packages/m3-0.4.4-py2.7.egg/m3/m3_common.py", line 486, in read_binfile
    self.hexencoded = m3_common.read_binfile_static(binfile)
  File "/usr/local/lib/python2.7/site-packages/m3-0.4.4-py2.7.egg/m3/m3_common.py", line 465, in read_binfile_static
    if guess_type_is_hex(binfile):
  File "/usr/local/lib/python2.7/site-packages/m3-0.4.4-py2.7.egg/m3/m3_common.py", line 457, in guess_type_is_hex
    for line in open(binfile):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x91 in position 4: invalid start byte

=====================================================================
 Patch that will catch the exception and just return false
=====================================================================
```
$ git diff
diff --git a/m3/m3_common.py b/m3/m3_common.py
index 8339a08..015cda0 100644
--- a/m3/m3_common.py
+++ b/m3/m3_common.py
@@ -454,12 +454,15 @@ class m3_common(object):
     @staticmethod
     def read_binfile_static(binfile):
         def guess_type_is_hex(binfile):
-            for line in open(binfile):
-                for c in line.strip():
-                    c = ord(c)
-                    if c < 0x20 or c > 0x7a:
-                        return False
-            return True
+            try:
+                for line in open(binfile):
+                    for c in line.strip():
+                        c = ord(c)
+                        if c < 0x20 or c > 0x7a:
+                            return False
+                return True
+            except UnicodeDecodeError:
+                return False

         if guess_type_is_hex(binfile):
             binfd = open(binfile, 'r')
```

**Comment by ppannuto** [comment]
Fixed by #3
